// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbbqoxymvcoxetiyejm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YmJxb3h5bXZjb3hldGl5ZWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDEwNDgsImV4cCI6MjA3MzY3NzA0OH0.Yv5gXnXj2buI6jW93WBa7hM4_oXggJU3y44UdyMKS7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
